#pragma once

namespace AsciiEngine
{
	// From Windows.h
	enum WindowsColor
	{
		FOREGROUND_BLUE      = 0x0001, // text color contains blue.
		FOREGROUND_GREEN     = 0x0002, // text color contains green.
		FOREGROUND_RED       = 0x0004, // text color contains red.
		FOREGROUND_INTENSITY = 0x0008, // text color is intensified.
		//BACKGROUND_BLUE      = 0x0010, // background color contains blue.
		//BACKGROUND_GREEN     = 0x0020, // background color contains green.
		//BACKGROUND_RED       = 0x0040, // background color contains red.
		//BACKGROUND_INTENSITY = 0x0080, // background color is intensified.
	};

	enum class Color
	{
		BLACK = 0,
		DARK_BLUE = FOREGROUND_BLUE,
		DARK_GREEN = FOREGROUND_GREEN,
		DARK_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
		DARK_RED = FOREGROUND_RED,
		DARK_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
		DARK_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
		DARK_GRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
		GRAY = FOREGROUND_INTENSITY,
		BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
		GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
		CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
		RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
		MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
		YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
		WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	};
}